[package]
name = "slidePuzzleSolver"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
reqwest = "0.12.8"
serde = { version = "1.0.213" , features = ["derive"]}
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
